[package]
name = "fs-stat"
version = "0.1.2"
authors = [ "Viktor Kuroljov <viktor@ku.family>" ]
edition = "2018"

[dependencies]
libc = "0.2"
errno = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"
